#!/bin/bash
# ============================================================================
# 3-GPU suite for candidate-key cache evaluation.
#
# Layout:
#   GPU_BASE   -> strict baseline: cache OFF
#   GPU_CACHE  -> strict compare:  cache ON
#   GPU_STRESS -> cache ON under a stronger multi-query workload
#
# Recommended use:
#   1. GPU_BASE vs GPU_CACHE tells us whether candidate-key reuse actually
#      reduces routing cost without changing answer quality.
#   2. GPU_STRESS tells us whether the reuse benefit gets larger when one doc
#      serves more queries, which is exactly the regime where this optimization
#      should matter most.
#
# Usage:
#   cd ~/working_place/topic_selective_kv
#   bash scripts_qmsum/run_qmsum_candidate_key_cache_3gpu_suite.sh
# ============================================================================

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

GPU_BASE=${GPU_BASE:-2}
GPU_CACHE=${GPU_CACHE:-3}
GPU_STRESS=${GPU_STRESS:-4}

COMPARE_START_DOC=${COMPARE_START_DOC:-5}
COMPARE_END_DOC=${COMPARE_END_DOC:-10}
COMPARE_MAX_QUERIES=${COMPARE_MAX_QUERIES:-5}

STRESS_START_DOC=${STRESS_START_DOC:-5}
STRESS_END_DOC=${STRESS_END_DOC:-10}
STRESS_MAX_QUERIES=${STRESS_MAX_QUERIES:-0}

NUM_NODES=${NUM_NODES:-4}
ROUTE_TOP_K=${ROUTE_TOP_K:-12}
QK_SCORE_BATCH_SIZE=${QK_SCORE_BATCH_SIZE:-64}

DYNAMIC_SUMMARY_TOP_K=${DYNAMIC_SUMMARY_TOP_K:-16}
DYNAMIC_DETAIL_TOP_K=${DYNAMIC_DETAIL_TOP_K:-12}
DYNAMIC_BALANCED_TOP_K=${DYNAMIC_BALANCED_TOP_K:-12}

ROUTE_CANDIDATE_PREFILTER=${ROUTE_CANDIDATE_PREFILTER:-lexical}
ROUTE_CANDIDATE_PREFILTER_FACTOR=${ROUTE_CANDIDATE_PREFILTER_FACTOR:-6}
ROUTE_CANDIDATE_PREFILTER_MIN_KEEP=${ROUTE_CANDIDATE_PREFILTER_MIN_KEEP:-48}
ROUTE_CANDIDATE_PREFILTER_MAX_KEEP=${ROUTE_CANDIDATE_PREFILTER_MAX_KEEP:-128}

ANSWER_EVIDENCE_ORDER=${ANSWER_EVIDENCE_ORDER:-qk_then_time}
SELECTED_ANSWER_CONTEXT_MODE=${SELECTED_ANSWER_CONTEXT_MODE:-turns}
ANSWER_PROMPT_STYLE=${ANSWER_PROMPT_STYLE:-strict}
ANSWER_EVIDENCE_MAX_ENTRIES=${ANSWER_EVIDENCE_MAX_ENTRIES:-80}
ANSWER_EVIDENCE_MAX_CHARS=${ANSWER_EVIDENCE_MAX_CHARS:-600}

FETCH_BANDWIDTH_GBPS=${FETCH_BANDWIDTH_GBPS:-25.0}
PER_NODE_RTT_MS=${PER_NODE_RTT_MS:-1.0}
PER_SEGMENT_OVERHEAD_MS=${PER_SEGMENT_OVERHEAD_MS:-0.15}
DECODE_STARTUP_MS=${DECODE_STARTUP_MS:-15.0}
QUERY_TOKENIZER_WARMUP=${QUERY_TOKENIZER_WARMUP:-1}

SUITE_ROOT=${SUITE_ROOT:-logs/qmsum_candidate_key_cache_3gpu_suite}
COMPARE_LOG_ROOT="$SUITE_ROOT/compare"
STRESS_LOG_DIR="$SUITE_ROOT/stress_cache_on"

mkdir -p "$SUITE_ROOT"

echo "============================================================"
echo " QMSum Candidate-Key Cache 3-GPU Suite"
echo " GPU_BASE=$GPU_BASE  (cache=0)"
echo " GPU_CACHE=$GPU_CACHE (cache=1)"
echo " GPU_STRESS=$GPU_STRESS (cache=1, stronger multi-query run)"
echo " compare_docs=$COMPARE_START_DOC:$COMPARE_END_DOC"
echo " compare_max_queries=$COMPARE_MAX_QUERIES"
echo " stress_docs=$STRESS_START_DOC:$STRESS_END_DOC"
echo " stress_max_queries=$STRESS_MAX_QUERIES"
echo " QK_SCORE_BATCH_SIZE=$QK_SCORE_BATCH_SIZE"
echo " QUERY_TOKENIZER_WARMUP=$QUERY_TOKENIZER_WARMUP"
echo " ROUTE_TOP_K=$ROUTE_TOP_K"
echo " DYNAMIC_DETAIL_TOP_K=$DYNAMIC_DETAIL_TOP_K"
echo " PREFILTER=${ROUTE_CANDIDATE_PREFILTER} factor=$ROUTE_CANDIDATE_PREFILTER_FACTOR min=$ROUTE_CANDIDATE_PREFILTER_MIN_KEEP max=$ROUTE_CANDIDATE_PREFILTER_MAX_KEEP"
echo "============================================================"

GPU_A="$GPU_BASE" \
GPU_B="$GPU_CACHE" \
CACHE_A=0 \
CACHE_B=1 \
START_DOC="$COMPARE_START_DOC" \
END_DOC="$COMPARE_END_DOC" \
MAX_QUERIES="$COMPARE_MAX_QUERIES" \
NUM_NODES="$NUM_NODES" \
ROUTE_TOP_K="$ROUTE_TOP_K" \
QK_SCORE_BATCH_SIZE="$QK_SCORE_BATCH_SIZE" \
DYNAMIC_SUMMARY_TOP_K="$DYNAMIC_SUMMARY_TOP_K" \
DYNAMIC_DETAIL_TOP_K="$DYNAMIC_DETAIL_TOP_K" \
DYNAMIC_BALANCED_TOP_K="$DYNAMIC_BALANCED_TOP_K" \
ROUTE_CANDIDATE_PREFILTER="$ROUTE_CANDIDATE_PREFILTER" \
ROUTE_CANDIDATE_PREFILTER_FACTOR="$ROUTE_CANDIDATE_PREFILTER_FACTOR" \
ROUTE_CANDIDATE_PREFILTER_MIN_KEEP="$ROUTE_CANDIDATE_PREFILTER_MIN_KEEP" \
ROUTE_CANDIDATE_PREFILTER_MAX_KEEP="$ROUTE_CANDIDATE_PREFILTER_MAX_KEEP" \
ANSWER_EVIDENCE_ORDER="$ANSWER_EVIDENCE_ORDER" \
SELECTED_ANSWER_CONTEXT_MODE="$SELECTED_ANSWER_CONTEXT_MODE" \
ANSWER_PROMPT_STYLE="$ANSWER_PROMPT_STYLE" \
ANSWER_EVIDENCE_MAX_ENTRIES="$ANSWER_EVIDENCE_MAX_ENTRIES" \
ANSWER_EVIDENCE_MAX_CHARS="$ANSWER_EVIDENCE_MAX_CHARS" \
FETCH_BANDWIDTH_GBPS="$FETCH_BANDWIDTH_GBPS" \
PER_NODE_RTT_MS="$PER_NODE_RTT_MS" \
PER_SEGMENT_OVERHEAD_MS="$PER_SEGMENT_OVERHEAD_MS" \
DECODE_STARTUP_MS="$DECODE_STARTUP_MS" \
QUERY_TOKENIZER_WARMUP="$QUERY_TOKENIZER_WARMUP" \
LOG_ROOT="$COMPARE_LOG_ROOT" \
bash "$SCRIPT_DIR/run_qmsum_candidate_key_cache_compare_dual_gpu.sh" &
PID_COMPARE=$!

GPU_ID="$GPU_STRESS" \
START_DOC="$STRESS_START_DOC" \
END_DOC="$STRESS_END_DOC" \
MAX_QUERIES="$STRESS_MAX_QUERIES" \
NUM_NODES="$NUM_NODES" \
ROUTE_TOP_K="$ROUTE_TOP_K" \
QK_SCORE_BATCH_SIZE="$QK_SCORE_BATCH_SIZE" \
DYNAMIC_ROUTE_BUDGET=1 \
DYNAMIC_SUMMARY_TOP_K="$DYNAMIC_SUMMARY_TOP_K" \
DYNAMIC_DETAIL_TOP_K="$DYNAMIC_DETAIL_TOP_K" \
DYNAMIC_BALANCED_TOP_K="$DYNAMIC_BALANCED_TOP_K" \
ROUTE_CANDIDATE_PREFILTER="$ROUTE_CANDIDATE_PREFILTER" \
ROUTE_CANDIDATE_PREFILTER_FACTOR="$ROUTE_CANDIDATE_PREFILTER_FACTOR" \
ROUTE_CANDIDATE_PREFILTER_MIN_KEEP="$ROUTE_CANDIDATE_PREFILTER_MIN_KEEP" \
ROUTE_CANDIDATE_PREFILTER_MAX_KEEP="$ROUTE_CANDIDATE_PREFILTER_MAX_KEEP" \
CACHE_CANDIDATE_KEYS=1 \
ANSWER_EVIDENCE_ORDER="$ANSWER_EVIDENCE_ORDER" \
SELECTED_ANSWER_CONTEXT_MODE="$SELECTED_ANSWER_CONTEXT_MODE" \
ANSWER_PROMPT_STYLE="$ANSWER_PROMPT_STYLE" \
ANSWER_EVIDENCE_MAX_ENTRIES="$ANSWER_EVIDENCE_MAX_ENTRIES" \
ANSWER_EVIDENCE_MAX_CHARS="$ANSWER_EVIDENCE_MAX_CHARS" \
FETCH_BANDWIDTH_GBPS="$FETCH_BANDWIDTH_GBPS" \
PER_NODE_RTT_MS="$PER_NODE_RTT_MS" \
PER_SEGMENT_OVERHEAD_MS="$PER_SEGMENT_OVERHEAD_MS" \
DECODE_STARTUP_MS="$DECODE_STARTUP_MS" \
QUERY_TOKENIZER_WARMUP="$QUERY_TOKENIZER_WARMUP" \
CASE_SUMMARY_TAG="keycache_suite_stress_batch${QK_SCORE_BATCH_SIZE}_detail${DYNAMIC_DETAIL_TOP_K}_docs${STRESS_START_DOC}_${STRESS_END_DOC}_q${STRESS_MAX_QUERIES}" \
LOG_DIR="$STRESS_LOG_DIR" \
bash "$SCRIPT_DIR/run_qmsum_mainline_answer_eval.sh" &
PID_STRESS=$!

wait $PID_COMPARE
STATUS_COMPARE=$?

wait $PID_STRESS
STATUS_STRESS=$?

echo ""
echo "============================================================"
echo " 3-GPU suite finished"
echo " compare status=$STATUS_COMPARE"
echo " stress  status=$STATUS_STRESS"
echo " compare summary: $COMPARE_LOG_ROOT/summary.txt"
echo " stress logs:     $STRESS_LOG_DIR"
echo "============================================================"
